apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: hello
labels:
  app: hello
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: dedyyyy/hello:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: hello

